// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "1e9a4cc4-a481-4615-b33b-e96b87d59b0d";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onMessageChange();
void onSetTimeChange();
void onTempatureSetChange();

String message;
int cTemperature;
int setTime;
int tempatureSet;
CloudTime timeLeft;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(message, READWRITE, ON_CHANGE, onMessageChange, 1);
  ArduinoCloud.addProperty(cTemperature, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(setTime, READWRITE, ON_CHANGE, onSetTimeChange);
  ArduinoCloud.addProperty(tempatureSet, READWRITE, ON_CHANGE, onTempatureSetChange, 1);
  ArduinoCloud.addProperty(timeLeft, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
